### ISSUE TITLE
Remove noremap = true in keybindings.lua

### ISSUE THREAD

**Issue by salcode** [arusahni/dotfiles#3]
This is a very cool repo - thanks for sharing it. It is great to see what others are doing.

One small note, since you're using `vim.keymap.set()` in your `map()` function, I think you can remove explicitly setting `noremap = true`.

https://github.com/arusahni/dotfiles/blob/fd6bf6435763f6d29e95ec3c42cdc33aa2cf6952/nvim/lua/keybindings.lua#L3-L9

From the [vim.keymap.set()](https://neovim.io/doc/user/lua.html#vim.keymap.set%28%29) documentation.

> remap: (boolean) Make the mapping recursive. This is the inverse of the "noremap" option from [nvim_set_keymap()](https://neovim.io/doc/user/api.html#nvim_set_keymap()). Defaults to `false`.

If I'm reading this correctly, since the default value for `remap` is `false`, there is no need to explicitly set `noremap = true`.

**Comment by arusahni** [comment]
Hi, interesting point! That inference makes sense given the docs for `noremap`:

>  noremap: Always overridden with the inverse of "remap" (see below). 

I'll give it a spin today. I'm always down to simplify things.

**Comment by arusahni** [comment]
I trialed it all this week and it functioned as expected. Thanks for pointing this out!

**Comment by salcode** [comment]
Awesome - thanks for sharing the results!
